### ISSUE TITLE
Startup refresh

### ISSUE THREAD

**Issue by j3k0** [iridescent-dev/iap-swift-lib#18]
A propos de #16 

Il me semble que la lib fait un refresh au démarrage. Est-ce que cela appèle `InAppPurchase.refresh()`? Sinon, l'app risque de faire un `refresh()` juste après avoir démarrer (en entrant sur la première vue)... Donc il y aura un double refresh.

Je me demande quand même si cette logique d'empêcher les double refresh n'aurait pas du être dans le RefreshService et ProductService, non?

**Comment by iridescent-dev** [comment]
Pas de double refresh lors de l'initialisation.
